name: Checks

on: [push, pull_request]

jobs:
  checks:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # install dependencies from yarn.lock
      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile

      # Run linting with yarn
      - run: yarn lint
